### ISSUE TITLE
annotation tool for detectron2

### ISSUE THREAD

**Issue by sourangshupal** [Tony607/detectron2_instance_segmentation_demo#1]
Which annotation tool you are using for labelling the dataset???

**Comment by Tony607** [comment]
If you want to know how to create COCO datasets, please read my previous post — [How to create custom COCO data set for instance segmentation](https://www.dlology.com/blog/how-to-create-custom-coco-data-set-for-instance-segmentation/).
An alternative is the VGG Image Annotator (VIA) tool - [via-2.0.8.zip](http://www.robots.ox.ac.uk/~vgg/software/via/downloads/via-2.0.8.zip).
